default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  reconnect: true
  
development:
  <<: *default

test:
  <<: *default
  database: test